//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshop2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpucooler
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public Nullable<int> FanConnections { get; set; }
        public string CoolingMethod { get; set; }
        public string Socket { get; set; }
        public Nullable<int> DiameterFan { get; set; }
        public Nullable<int> Min_RotationSpeed { get; set; }
        public Nullable<int> Max_RotationSpeed { get; set; }
        public Nullable<float> Min_SoundProduction { get; set; }
        public Nullable<float> Max_SoundProduction { get; set; }
        public Nullable<int> HeatPipes { get; set; }
        public Nullable<float> Weight { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> Depth { get; set; }
        public Nullable<float> Height { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Name { get; set; }
    
        public virtual product product { get; set; }
    }
}
