//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshop2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class internalharddisk
    {
        public int InternalHDDId { get; set; }
        public string Brand { get; set; }
        public string StorageType { get; set; }
        public Nullable<int> HDDSpeed { get; set; }
        public Nullable<int> Cache { get; set; }
        public Nullable<float> HDDFormat { get; set; }
        public Nullable<float> Height { get; set; }
        public string InternalHDDDiskcol { get; set; }
    }
}
