//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshop2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class motherboard
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string FormatMotherboard { get; set; }
        public Nullable<int> Socket { get; set; }
        public string Chipset { get; set; }
        public Nullable<int> ClockSpeedMemoryModule { get; set; }
        public Nullable<int> Max_AmountOfMemory { get; set; }
        public Nullable<int> MemoryLockedTotal { get; set; }
        public string Memory { get; set; }
        public Nullable<int> PXIx16 { get; set; }
        public Nullable<int> PCIx8 { get; set; }
        public Nullable<int> PCix4 { get; set; }
        public Nullable<int> PCIx2 { get; set; }
        public Nullable<int> PCILocks { get; set; }
        public Nullable<int> PCIMini { get; set; }
        public Nullable<int> EthernetPorts { get; set; }
        public Nullable<sbyte> BuiltINWifi { get; set; }
        public Nullable<sbyte> Bluetooth { get; set; }
        public Nullable<sbyte> FireWire { get; set; }
        public Nullable<int> USB2Ports { get; set; }
        public Nullable<int> USB3Ports { get; set; }
        public Nullable<sbyte> Thunderbolt { get; set; }
        public Nullable<sbyte> PS2 { get; set; }
        public Nullable<int> SATA300 { get; set; }
        public Nullable<int> SATA600 { get; set; }
        public Nullable<int> mSATA { get; set; }
        public Nullable<int> M2Connections { get; set; }
        public string Raid { get; set; }
        public Nullable<int> SpeakerChannels { get; set; }
        public Nullable<sbyte> OpticalConnection { get; set; }
        public string AudioProcessor { get; set; }
        public Nullable<sbyte> VGAPort { get; set; }
        public Nullable<sbyte> DVIPort { get; set; }
        public Nullable<sbyte> HDMIPort { get; set; }
        public Nullable<sbyte> DisplayPort { get; set; }
        public string ChipsetCooler { get; set; }
        public Nullable<int> CaseFanConnections { get; set; }
        public Nullable<sbyte> UEFIBIOS { get; set; }
        public Nullable<sbyte> NVIDEASLI { get; set; }
        public Nullable<sbyte> CrossfireX { get; set; }
        public Nullable<sbyte> KillerNIC { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> Depth { get; set; }
        public Nullable<float> Height { get; set; }
    }
}
