//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshop2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class powersupply
    {
        public int PowerSupplyId { get; set; }
        public string Brand { get; set; }
        public string VersionFOrmFactor { get; set; }
        public Nullable<sbyte> Modular { get; set; }
        public Nullable<float> DiamterFan { get; set; }
        public Nullable<int> Power { get; set; }
        public string Certification { get; set; }
        public Nullable<int> AverageLifespawn { get; set; }
        public Nullable<int> ATX20 { get; set; }
        public Nullable<int> CPU8 { get; set; }
        public Nullable<int> CPU4 { get; set; }
        public Nullable<int> CPU4p4 { get; set; }
        public Nullable<int> PCIExpress6pin { get; set; }
        public Nullable<int> PCIExpress6pin2pin { get; set; }
        public Nullable<int> IDE { get; set; }
        public Nullable<int> SAtA { get; set; }
        public Nullable<int> FDD { get; set; }
        public Nullable<sbyte> currentspkes { get; set; }
        public Nullable<sbyte> Overvoltag { get; set; }
        public Nullable<sbyte> SurgePortection { get; set; }
        public Nullable<sbyte> UnderPressure { get; set; }
        public Nullable<sbyte> Overload { get; set; }
        public Nullable<sbyte> ShortCircuit { get; set; }
        public Nullable<sbyte> OverheatingProtection { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> Depth { get; set; }
        public Nullable<float> Height { get; set; }
    }
}
