//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webshop2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wishlist
    {
        public int ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ProductName { get; set; }
    
        public virtual ram ram { get; set; }
        public virtual user user { get; set; }
    }
}
